#ifndef MAHIT_H
#define MAHIT_H

/**
 * Extract read-read pairs with multiple alignments from Minimap2 PAF file.
 * This header file processes a PAF file generated by minimap2 in all-vs-all mode
 * and identifies pairs of reads that have multiple alignment relationships.
 **/

#include "paf.h"
#include "robin_hood.h"
#include <vector>
#include <algorithm>

typedef robin_hood::unordered_map<std::string, std::string> r_pair;                  // read-read pair
typedef robin_hood::unordered_map<std::string, std::vector<tr_paf_rec_t>> tn_alns;   // tn -> all alignments
typedef robin_hood::unordered_map<std::string, tn_alns> tr_p_aln_info;               // qn->{tn->all alignments}
typedef robin_hood::unordered_map<std::string, int> p_ct;                            // pair number counter
typedef robin_hood::unordered_map<std::string, p_ct> r_pair_vec;                     // read-read pairs
void f_mul_aln_ps(const char *fn, r_pair_vec &mul_aln_ps);                           // find multiple-alignment read-read pairs
void f_aln_ps_tr(const r_pair_vec &mul_aln_ps, r_pair &tr_ps);                       // for each refence read to find a mutiple-alignment pair (have maximum number of multiple alignments) for inferring tandem repeat
void f_tr_aln_info(const char *fn, tr_p_aln_info &tr_aln_lib, const int &l_cutoff);  // extracts read-read alignment information from a PAF file to infer tandem repeats. This is the main function.
void f_tr_aln_info_hifiasm(const char *fn, tr_p_aln_info &tr_aln_lib);               // test
void f_tr_aln_info_omp(const char *fn, tr_p_aln_info &tr_aln_lib, int &num_threads); // muti-thread version of f_tr_aln_info
#endif